version: "3.11"

services:
  supply_tracker:
    build: .   # Uses your existing Dockerfile in the same folder
    container_name: supply_tracker
    ports:
      - "5000:5000"   # Expose Flask/Gunicorn on port 5000
    env_file:
      - .env
    volumes:
      - job_data:/app/job_data   # Persistent storage for marker file
    restart: always   # Auto-restart if container stops/crashes

volumes:
  job_data: {}
