version: "3.11"

services:
  supply_tracker:
    build: .   # Uses your existing Dockerfile in the same folder
    container_name: supply_tracker
    ports:
      - "5000:5000"   # Expose Flask/Gunicorn on port 5000
    env_file:
      - .env
    volumes:
      - myapp-data:/var/lib/myapp   # Persistent storage for marker file
    user: "1000:1000"   # Run container as your host user (fixes permissions)
    restart: always     # Auto-restart if container stops/crashes

volumes:
  myapp-data: {}
