services:
  - type: web
    name: supply-tracker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "false"
    healthCheckPath: /